//-============================================================
//
//         This class has been generated by POGO
//      (Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================


Files generated:
===============
Serial.cpp:        Source code for the Serial class and its commands.
                        This class is derived from DeviceImpl_2 class.
                        It represents the CORBA servant obbject which
                        will be accessed from the network.
                        All commands which can be executed on the
                        Serial are implemented in this file.

Serial.h:  Include for the Serial class.
                    Server class prototypes and descriptions.

SerialClass.cpp:   A singleton class derived fromSerial.
                        It implements the command list and all properties
                        and methods required by the Serial once per process

SerialClass.h:	Include for the SerialClass root class.
                        This class is represents the singleton class for
                        the Serial device class.
                        It contains all properties and methods which the 
                        Serial requires only once e.g. the commands.

main.cpp:		C++ source for a TANGO device server main.
                        The main rule is to initialise (and create) the Tango
                        system and to create the DServerClass singleton.
                        The main should be the same for every Tango device server.

ClassFactory.cpp:	C++ source for the class_factory method of the DServer
                        device class. This method is responsible to create
                        all class singletin for a device server. It is called
                        at device server startup
