static const char *RcsId = "$Header: /users/chaize/newsvn/cvsroot/Communication/SerialLine/src/SerialStateMachine.cpp,v 1.2 2005-05-31 08:03:41 xavela Exp $";
//+=============================================================================
//
// file :         SerialStateMachine.cpp
//
// description :  C++ source for the Serial and its alowed. 
//                method for commands and attributes
//
// project :      TANGO Device Server
//
// $Author: xavela $
//
// $Revision: 1.2 $
//
// $Log: not supported by cvs2svn $
// Revision 1.1  2005/03/22 08:02:31  taurel
// - Ported to Tango V5
// - Added small changed from AG in the Windows part (One Sleep to calm down thing and
//   some management of 0 character)
//
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#include <tango.h>
#include <Serial.h>
#include <SerialClass.h>

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace Serial_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================


//=================================================
//		Commands Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		Serial::is_DevSerWriteString_allowed
// 
// description : 	Execution allowed for DevSerWriteString command.
//
//-----------------------------------------------------------------------------
bool Serial::is_DevSerWriteString_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Serial::is_DevSerWriteChar_allowed
// 
// description : 	Execution allowed for DevSerWriteChar command.
//
//-----------------------------------------------------------------------------
bool Serial::is_DevSerWriteChar_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Serial::is_DevSerReadString_allowed
// 
// description : 	Execution allowed for DevSerReadString command.
//
//-----------------------------------------------------------------------------
bool Serial::is_DevSerReadString_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Serial::is_DevSerReadChar_allowed
// 
// description : 	Execution allowed for DevSerReadChar command.
//
//-----------------------------------------------------------------------------
bool Serial::is_DevSerReadChar_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Serial::is_WriteRead_allowed
// 
// description : 	Execution allowed for WriteRead command.
//
//-----------------------------------------------------------------------------
bool Serial::is_WriteRead_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Serial::is_DevSerGetNChar_allowed
// 
// description : 	Execution allowed for DevSerGetNChar command.
//
//-----------------------------------------------------------------------------
bool Serial::is_DevSerGetNChar_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Serial::is_DevSerReadNChar_allowed
// 
// description : 	Execution allowed for DevSerReadNChar command.
//
//-----------------------------------------------------------------------------
bool Serial::is_DevSerReadNChar_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Serial::is_DevSerReadRaw_allowed
// 
// description : 	Execution allowed for DevSerReadRaw command.
//
//-----------------------------------------------------------------------------
bool Serial::is_DevSerReadRaw_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Serial::is_DevSerReadLine_allowed
// 
// description : 	Execution allowed for DevSerReadLine command.
//
//-----------------------------------------------------------------------------
bool Serial::is_DevSerReadLine_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Serial::is_DevSerFlush_allowed
// 
// description : 	Execution allowed for DevSerFlush command.
//
//-----------------------------------------------------------------------------
bool Serial::is_DevSerFlush_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Serial::is_DevSerSetParameter_allowed
// 
// description : 	Execution allowed for DevSerSetParameter command.
//
//-----------------------------------------------------------------------------
bool Serial::is_DevSerSetParameter_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Serial::is_DevSerSetTimeout_allowed
// 
// description : 	Execution allowed for DevSerSetTimeout command.
//
//-----------------------------------------------------------------------------
bool Serial::is_DevSerSetTimeout_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Serial::is_DevSerSetParity_allowed
// 
// description : 	Execution allowed for DevSerSetParity command.
//
//-----------------------------------------------------------------------------
bool Serial::is_DevSerSetParity_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Serial::is_DevSerSetCharLength_allowed
// 
// description : 	Execution allowed for DevSerSetCharLength command.
//
//-----------------------------------------------------------------------------
bool Serial::is_DevSerSetCharLength_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Serial::is_DevSerSetStopbit_allowed
// 
// description : 	Execution allowed for DevSerSetStopbit command.
//
//-----------------------------------------------------------------------------
bool Serial::is_DevSerSetStopbit_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Serial::is_DevSerSetBaudrate_allowed
// 
// description : 	Execution allowed for DevSerSetBaudrate command.
//
//-----------------------------------------------------------------------------
bool Serial::is_DevSerSetBaudrate_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Serial::is_DevSerSetNewline_allowed
// 
// description : 	Execution allowed for DevSerSetNewline command.
//
//-----------------------------------------------------------------------------
bool Serial::is_DevSerSetNewline_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Serial::is_DevSerReadRetry_allowed
// 
// description : 	Execution allowed for DevSerReadRetry command.
//
//-----------------------------------------------------------------------------
bool Serial::is_DevSerReadRetry_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		Serial::is_DevSerReadNBinData_allowed
// 
// description : 	Execution allowed for DevSerReadNBinData command.
//
//-----------------------------------------------------------------------------
bool Serial::is_DevSerReadNBinData_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

}	// namespace Serial_ns
